# Generated by Django 4.1.6 on 2023-02-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50, verbose_name='category_name')),
                ('logo_category', models.ImageField(upload_to='logo_category', verbose_name='category_logo')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
