# Generated by Django 4.1.6 on 2023-02-11 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100, verbose_name='name_product')),
                ('description_product', models.TextField(verbose_name='description_product')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('deleted', models.BooleanField(default=False)),
                ('category_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.modelcategory', verbose_name='category_product')),
            ],
        ),
    ]
