# Generated by Django 4.1.6 on 2023-02-11 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_instruction', models.TextField(verbose_name='text_instruction')),
                ('image_instruction', models.ImageField(blank=True, null=True, upload_to='instruction_image')),
                ('deleted', models.BooleanField(default=False)),
                ('product_instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.modelproducts', verbose_name='product_instruction')),
            ],
        ),
    ]
