# Generated by Django 4.1.6 on 2023-02-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinstruction',
            name='name_instruction',
            field=models.CharField(default=1, max_length=255, verbose_name='name_instruction'),
            preserve_default=False,
        ),
    ]
